# Imagem base do Nginx
FROM nginx:alpine

# Remove o conteúdo padrão do Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia os arquivos do frontend para o Nginx
COPY . /usr/share/nginx/html

# Expõe a porta 80
EXPOSE 8080
