# Imagem base com Python
FROM python:3.11-slim

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do frontend para o contêiner
COPY . /app

# Expõe a porta 8080
EXPOSE 8080

# Inicia um servidor HTTP simples
CMD ["python", "-m", "http.server", "8080"]
