# Imagem base com Python
FROM python:3.11-slim

# Define diretório de trabalho
WORKDIR /app

# Copia os arquivos do backend
COPY . /app

# Instala dependências
RUN pip install flask flask-cors

# Expõe a porta padrão do Flask
EXPOSE 5000

# Comando para iniciar o servidor Flask
CMD ["python", "app.py"]
