FROM python:3.11-slim

WORKDIR /app

COPY . .

# Instala as dependências do PostgreSQL e as bibliotecas Python
RUN apt-get update && apt-get install -y gcc libpq-dev && \
    pip install flask flask-cors psycopg2-binary

EXPOSE 5000

CMD ["python", "app.py"]
